/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Oddman
 */
public class RPG5_BATTLE1_DODGE extends javax.swing.JFrame {

    /**
     * Creates new form RPG5_BATTLE1_DODGE
     */
    public RPG5_BATTLE1_DODGE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RPG5_WEST = new javax.swing.JPanel();
        GameText14 = new javax.swing.JLabel();
        ATTACK = new javax.swing.JButton();
        DODGE = new javax.swing.JButton();
        Title2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RPG5_WEST.setBackground(new java.awt.Color(0, 0, 0));

        GameText14.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        GameText14.setForeground(new java.awt.Color(255, 255, 255));
        GameText14.setText("<html> * Just as you chose to dodge, the three rotfiends come barrelling at you <br> * Good choice! <br> * Maybe you should follow the steps on the note... <br> * But quick! Those monsters wont give up just yet!");

        ATTACK.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        ATTACK.setText("ATTACK");
        ATTACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATTACKActionPerformed(evt);
            }
        });

        DODGE.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        DODGE.setText("DODGE");
        DODGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DODGEActionPerformed(evt);
            }
        });

        Title2.setFont(new java.awt.Font("Dinarjev Republika", 0, 48)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("In the mists of aeriden");
        Title2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout RPG5_WESTLayout = new javax.swing.GroupLayout(RPG5_WEST);
        RPG5_WEST.setLayout(RPG5_WESTLayout);
        RPG5_WESTLayout.setHorizontalGroup(
            RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_WESTLayout.createSequentialGroup()
                .addGroup(RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(ATTACK)
                        .addGap(92, 92, 92)
                        .addComponent(DODGE))
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(GameText14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Title2)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        RPG5_WESTLayout.setVerticalGroup(
            RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_WESTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title2)
                .addGap(37, 37, 37)
                .addComponent(GameText14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ATTACK)
                    .addComponent(DODGE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_WEST, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_WEST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ATTACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATTACKActionPerformed
        this.setVisible(false);
        new RPG5_BATTLE2_ATTACK().setVisible(true);
    }//GEN-LAST:event_ATTACKActionPerformed

    private void DODGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DODGEActionPerformed
        this.setVisible(false);
        new RPG_DEATHSCREEN().setVisible(true);
    }//GEN-LAST:event_DODGEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPG5_BATTLE1_DODGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPG5_BATTLE1_DODGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPG5_BATTLE1_DODGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPG5_BATTLE1_DODGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPG5_BATTLE1_DODGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATTACK;
    private javax.swing.JButton DODGE;
    private javax.swing.JLabel GameText14;
    private javax.swing.JPanel RPG5_WEST;
    private javax.swing.JLabel Title2;
    // End of variables declaration//GEN-END:variables
}
