/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Oddman
 */
public class RPG5_BATTLE8_ATTACK extends javax.swing.JFrame {

    /**
     * Creates new form RPG5_BATTLE8_ATTACK
     */
    public RPG5_BATTLE8_ATTACK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RPG5_WEST = new javax.swing.JPanel();
        GameText14 = new javax.swing.JLabel();
        RETURN_TO_TOWN = new javax.swing.JButton();
        Title2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RPG5_WEST.setBackground(new java.awt.Color(0, 0, 0));

        GameText14.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        GameText14.setForeground(new java.awt.Color(255, 255, 255));
        GameText14.setText("<html> * You chose to attack <br>* Good choice! <br> * As you land your final attack on the 3 rotfiends, they explode <br> * You jump away just in time so that <br> &nbsp; its' guts down cover you <br> * You look at the mess of the corpses and decide to take <br> &nbsp; a heart so that the town guard may <br> &nbsp; finally trust you");

        RETURN_TO_TOWN.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        RETURN_TO_TOWN.setText("RETURN TO TOWN");
        RETURN_TO_TOWN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURN_TO_TOWNActionPerformed(evt);
            }
        });

        Title2.setFont(new java.awt.Font("Dinarjev Republika", 0, 48)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("In the mists of aeriden");
        Title2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout RPG5_WESTLayout = new javax.swing.GroupLayout(RPG5_WEST);
        RPG5_WEST.setLayout(RPG5_WESTLayout);
        RPG5_WESTLayout.setHorizontalGroup(
            RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPG5_WESTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GameText14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(RPG5_WESTLayout.createSequentialGroup()
                .addGroup(RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Title2))
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(RETURN_TO_TOWN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RPG5_WESTLayout.setVerticalGroup(
            RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_WESTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title2)
                .addGap(18, 18, 18)
                .addComponent(GameText14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(RETURN_TO_TOWN)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_WEST, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_WEST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RETURN_TO_TOWNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURN_TO_TOWNActionPerformed
        this.setVisible(false);
        new RPG_FINALTOWN().setVisible(true);
    }//GEN-LAST:event_RETURN_TO_TOWNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPG5_BATTLE8_ATTACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPG5_BATTLE8_ATTACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPG5_BATTLE8_ATTACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPG5_BATTLE8_ATTACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPG5_BATTLE8_ATTACK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameText14;
    private javax.swing.JButton RETURN_TO_TOWN;
    private javax.swing.JPanel RPG5_WEST;
    private javax.swing.JLabel Title2;
    // End of variables declaration//GEN-END:variables
}
