/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ERMCB6406
 */
public class RPG5_FIGHT extends javax.swing.JFrame {

    /**
     * Creates new form RPG5_FIGHT
     */
    public RPG5_FIGHT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RPG5_WEST = new javax.swing.JPanel();
        GameText14 = new javax.swing.JLabel();
        ATTACK = new javax.swing.JButton();
        DODGE = new javax.swing.JButton();
        Title2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RPG5_WEST.setBackground(new java.awt.Color(0, 0, 0));

        GameText14.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        GameText14.setForeground(new java.awt.Color(255, 255, 255));
        GameText14.setText("<html> * After you cleared the wild thistles, you continue <br> &nbsp; onwards, following the your insticts\n<br> &nbsp; and the small movements you spot in the corner of your eye <br> * As you creep forwards in\nthe thick, heavy mist, <br> &nbsp; you see a flash to your left <br> * Emerging from the whisping white \nessence, <br> &nbsp; the fowl smell of death and decay rips <br> &nbsp; through the once possible illusion of normalcy\n<br> * The source of the stench soon emerges to it's full glory <br> * Three goulish rotfiends sway heavily back\nand forth, <br> &nbsp; and you barley catch yourself from puking <br> * You draw your sword, and squeeze the grip <br>\n&nbsp; so hard your knuckles turn white <br> * You remind yourself about what you know <br> &nbsp; about these Necrophage class monsters\n<br> <br> * \"Rotfiends ressemble decomposing human bodies, but they have been stipped of <br> &nbsp; their skin, revealing  rotting layes of muscle. You can easily spot their presence from <br> &nbsp; the fowl, rotting stench that accompanies them. Lastly, the rotfiend's decomposing <br> &nbsp; body is filled with highly toxic emissions that can kill individuals if exposed for too long.\"\n<br> <br> * Before you can even think to turn away, the ghoulish creatures <br> &nbsp; notice your presence <br> * You may have forgotten to mention that they have a strict diet <br> &nbsp; that includes humans. <br> * You have no choice but to attack\n<br> * But wait! You faintly recall reading a note with a combo of attacks... <br> * Maybe that will be effective in killing the rotfiends?");

        ATTACK.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        ATTACK.setText("ATTACK");
        ATTACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATTACKActionPerformed(evt);
            }
        });

        DODGE.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        DODGE.setText("DODGE");
        DODGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DODGEActionPerformed(evt);
            }
        });

        Title2.setFont(new java.awt.Font("Dinarjev Republika", 0, 48)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("In the mists of aeriden");
        Title2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tw3_journal_rotfiend.png"))); // NOI18N

        javax.swing.GroupLayout RPG5_WESTLayout = new javax.swing.GroupLayout(RPG5_WEST);
        RPG5_WEST.setLayout(RPG5_WESTLayout);
        RPG5_WESTLayout.setHorizontalGroup(
            RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_WESTLayout.createSequentialGroup()
                .addGroup(RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Title2))
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(GameText14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(ATTACK)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(DODGE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RPG5_WESTLayout.setVerticalGroup(
            RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_WESTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title2)
                .addGap(29, 29, 29)
                .addComponent(GameText14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RPG5_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(DODGE))
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(ATTACK))
                    .addGroup(RPG5_WESTLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_WEST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_WEST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ATTACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATTACKActionPerformed
        this.setVisible(false);
        new RPG_DEATHSCREEN().setVisible(true);
    }//GEN-LAST:event_ATTACKActionPerformed

    private void DODGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DODGEActionPerformed
        this.setVisible(false);
        new RPG5_BATTLE1_DODGE().setVisible(true);
    }//GEN-LAST:event_DODGEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPG5_FIGHT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPG5_FIGHT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPG5_FIGHT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPG5_FIGHT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPG5_FIGHT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATTACK;
    private javax.swing.JButton DODGE;
    private javax.swing.JLabel GameText14;
    private javax.swing.JPanel RPG5_WEST;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
