/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ErMcB6406
 */
public class RPG5_NORTH_RIGHT_MUSHROOM extends javax.swing.JFrame {

    /**
     * Creates new form RPG5_NORTH_RIGHT_MUSHROOM
     */
    public RPG5_NORTH_RIGHT_MUSHROOM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Image4 = new javax.swing.JLabel();
        Image5 = new javax.swing.JLabel();
        GameText4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RPG5_NORTH_RIGHT_MUSHROOM = new javax.swing.JPanel();
        RETURN1 = new javax.swing.JButton();
        Title2 = new javax.swing.JLabel();
        GameText5 = new javax.swing.JLabel();
        Image3 = new javax.swing.JLabel();
        Image6 = new javax.swing.JLabel();

        Title1.setFont(new java.awt.Font("Wet Pet", 0, 48)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("In the mists of aeriden");
        Title1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel6.setText("jLabel2");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel7.setText("jLabel2");

        Image4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestbigwolf.png"))); // NOI18N
        Image4.setText("jLabel1");

        Image5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestbigwolf.png"))); // NOI18N
        Image5.setText("jLabel1");

        GameText4.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        GameText4.setForeground(new java.awt.Color(255, 255, 255));
        GameText4.setText("<html> * You choose to touch the glowing mushroom <br> * You sit down next to the\nfungi that spreads a pale glow around it <br> * You reach out and gently touch a mushroom cap <br> &nbsp; and a calm feeling envelops you <br>\n * You are suddenly startled when the mushroom begins to talk <br> * ... <br> * \"This is an Echo Mushroom. It repeats the last thing it <br> &nbsp; heard, over and over...\" <br> *... <br> * You curiousity proceeds you and\nyou begin touching <br> &nbsp; all the ones that surround you <br> * \"Thousands of people wishing together can't be wrong!\" <br> * \"I can't run any longer...Sombody, anybody...\" <br>\n* (You hear a passing conversation) <br> &nbsp; \"So? Don't you have any wishes to make?\" <br> &nbsp; \"...hmmm, just one, but...it's a bit stupid.\" <br> &nbsp; \"Don't say that! I won't laugh.\" <br> * \"Where am I...? It's so cold here... Someone help me... <br>\n&nbsp; ...Anyone...please...\" <br> * \"It's strangely silent...Why isn't there any noise? I just want <br> &nbsp; to hear...\"");

        jLabel8.setText("jLabel2");

        jLabel5.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RPG5_NORTH_RIGHT_MUSHROOM.setBackground(new java.awt.Color(0, 0, 0));

        RETURN1.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        RETURN1.setText("RETURN");
        RETURN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURN1ActionPerformed(evt);
            }
        });

        Title2.setFont(new java.awt.Font("Dinarjev Republika", 0, 60)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("In the mists of aeriden");
        Title2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        GameText5.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        GameText5.setForeground(new java.awt.Color(255, 255, 255));
        GameText5.setText("<html> * You choose to touch the glowing mushroom <br> * You sit down next to the\nfungi that spreads a pale glow around it <br> * You reach out and gently touch a mushroom cap <br> &nbsp; and a calm feeling envelops you <br>\n * You are suddenly startled when the mushroom begins to talk <br> * ... <br> * \"This is an Echo Mushroom. It repeats the last thing it <br> &nbsp; heard, over and over...\" <br> *... <br> * You curiousity proceeds you and\nyou begin touching <br> &nbsp; all the ones that surround you <br> * \"Thousands of people wishing together can't be wrong!\" <br> * \"I can't run any longer...Sombody, anybody...\" <br>\n* (You hear a passing conversation) <br> &nbsp; \"So? Don't you have any wishes to make?\" <br> &nbsp; \"...hmmm, just one, but...it's a bit stupid.\" <br> &nbsp; \"Don't say that! I won't laugh.\" <br> * \"Where am I...? It's so cold here... Someone help me... <br>\n&nbsp; ...Anyone...please...\" <br> * \"It's strangely silent...Why isn't there any noise? I just want <br> &nbsp; to hear...\"");

        Image3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestbigwolf.png"))); // NOI18N
        Image3.setText("jLabel1");

        Image6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestbigwolf.png"))); // NOI18N
        Image6.setText("jLabel1");

        javax.swing.GroupLayout RPG5_NORTH_RIGHT_MUSHROOMLayout = new javax.swing.GroupLayout(RPG5_NORTH_RIGHT_MUSHROOM);
        RPG5_NORTH_RIGHT_MUSHROOM.setLayout(RPG5_NORTH_RIGHT_MUSHROOMLayout);
        RPG5_NORTH_RIGHT_MUSHROOMLayout.setHorizontalGroup(
            RPG5_NORTH_RIGHT_MUSHROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPG5_NORTH_RIGHT_MUSHROOMLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Image3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GameText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Image6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPG5_NORTH_RIGHT_MUSHROOMLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(RPG5_NORTH_RIGHT_MUSHROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPG5_NORTH_RIGHT_MUSHROOMLayout.createSequentialGroup()
                        .addComponent(Title2)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPG5_NORTH_RIGHT_MUSHROOMLayout.createSequentialGroup()
                        .addComponent(RETURN1)
                        .addGap(403, 403, 403))))
        );
        RPG5_NORTH_RIGHT_MUSHROOMLayout.setVerticalGroup(
            RPG5_NORTH_RIGHT_MUSHROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_NORTH_RIGHT_MUSHROOMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title2)
                .addGroup(RPG5_NORTH_RIGHT_MUSHROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RPG5_NORTH_RIGHT_MUSHROOMLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(RPG5_NORTH_RIGHT_MUSHROOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Image3)
                            .addComponent(Image6)))
                    .addGroup(RPG5_NORTH_RIGHT_MUSHROOMLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(GameText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(RETURN1)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_NORTH_RIGHT_MUSHROOM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_NORTH_RIGHT_MUSHROOM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RETURN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURN1ActionPerformed
        this.setVisible(false);
        new RPG5_NORTH_RIGHT().setVisible(true);
    }//GEN-LAST:event_RETURN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_RIGHT_MUSHROOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_RIGHT_MUSHROOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_RIGHT_MUSHROOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_RIGHT_MUSHROOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPG5_NORTH_RIGHT_MUSHROOM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameText4;
    private javax.swing.JLabel GameText5;
    private javax.swing.JLabel Image3;
    private javax.swing.JLabel Image4;
    private javax.swing.JLabel Image5;
    private javax.swing.JLabel Image6;
    private javax.swing.JButton RETURN1;
    private javax.swing.JPanel RPG5_NORTH_RIGHT_MUSHROOM;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
