/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ErMcB6406
 */
public class RPG5_NORTH_LEFT_CONT1_NOTE2 extends javax.swing.JFrame {

    /**
     * Creates new form RPG5_NORTH_LEFT_CONT1_NOTE2
     */
    public RPG5_NORTH_LEFT_CONT1_NOTE2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        RPG5_NORTH_LEFT_CONT1_NOTE2 = new javax.swing.JPanel();
        GameText4 = new javax.swing.JLabel();
        RETURN = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel6.setText("jLabel2");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel5.setText("jLabel2");

        Title1.setFont(new java.awt.Font("Wet Pet", 0, 48)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("In the mists of aeriden");
        Title1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RPG5_NORTH_LEFT_CONT1_NOTE2.setBackground(new java.awt.Color(0, 0, 0));

        GameText4.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        GameText4.setForeground(new java.awt.Color(255, 255, 255));
        GameText4.setText("<html> * You feel like you should remember the note <br> * \"Dodge, attack, attack, dodge,<br> &nbsp; attack, dodge, attack, attack\" <br>* ... <br> * You are filled with determination");

        RETURN.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        RETURN.setText("RETURN");
        RETURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURNActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel14.setText("jLabel2");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wolfsmaller.png"))); // NOI18N
        jLabel15.setText("jLabel2");

        Title2.setFont(new java.awt.Font("Dinarjev Republika", 0, 48)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("In the mists of aeriden");
        Title2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Title2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout RPG5_NORTH_LEFT_CONT1_NOTE2Layout = new javax.swing.GroupLayout(RPG5_NORTH_LEFT_CONT1_NOTE2);
        RPG5_NORTH_LEFT_CONT1_NOTE2.setLayout(RPG5_NORTH_LEFT_CONT1_NOTE2Layout);
        RPG5_NORTH_LEFT_CONT1_NOTE2Layout.setHorizontalGroup(
            RPG5_NORTH_LEFT_CONT1_NOTE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_NORTH_LEFT_CONT1_NOTE2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GameText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(RPG5_NORTH_LEFT_CONT1_NOTE2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPG5_NORTH_LEFT_CONT1_NOTE2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RETURN)
                .addGap(226, 226, 226))
        );
        RPG5_NORTH_LEFT_CONT1_NOTE2Layout.setVerticalGroup(
            RPG5_NORTH_LEFT_CONT1_NOTE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPG5_NORTH_LEFT_CONT1_NOTE2Layout.createSequentialGroup()
                .addGroup(RPG5_NORTH_LEFT_CONT1_NOTE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RPG5_NORTH_LEFT_CONT1_NOTE2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel14))
                    .addGroup(RPG5_NORTH_LEFT_CONT1_NOTE2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Title2)
                        .addGap(31, 31, 31)
                        .addGroup(RPG5_NORTH_LEFT_CONT1_NOTE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(GameText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addComponent(RETURN)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_NORTH_LEFT_CONT1_NOTE2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPG5_NORTH_LEFT_CONT1_NOTE2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RETURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURNActionPerformed
        this.setVisible(false);
        new RPG5_NORTH_LEFT_CONT1().setVisible(true);
    }//GEN-LAST:event_RETURNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_LEFT_CONT1_NOTE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_LEFT_CONT1_NOTE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_LEFT_CONT1_NOTE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPG5_NORTH_LEFT_CONT1_NOTE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPG5_NORTH_LEFT_CONT1_NOTE2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameText4;
    private javax.swing.JButton RETURN;
    private javax.swing.JPanel RPG5_NORTH_LEFT_CONT1_NOTE2;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
